export const availableInstruments = [
  { value: "acoustic_grand_piano", label: "Acoustic Grand Piano" },
  { value: "bright_acoustic_piano", label: "Bright Acoustic Piano" },
  { value: "electric_grand_piano", label: "Electric Grand Piano" },
  { value: "honkytonk_piano", label: "Honky-tonk Piano" },
  { value: "electric_piano_1", label: "Electric Piano 1" },
  { value: "electric_piano_2", label: "Electric Piano 2" },
  { value: "harpsichord", label: "Harpsichord" },
  { value: "clavinet", label: "Clavinet" },
  { value: "celesta", label: "Celesta" },
  { value: "glockenspiel", label: "Glockenspiel" },
  { value: "music_box", label: "Music Box" },
  { value: "vibraphone", label: "Vibraphone" },
  { value: "marimba", label: "Marimba" },
  { value: "xylophone", label: "Xylophone" },
  { value: "tubular_bells", label: "Tubular Bells" },
  { value: "dulcimer", label: "Dulcimer" },
  { value: "drawbar_organ", label: "Drawbar Organ" },
  { value: "percussive_organ", label: "Percussive Organ" },
  { value: "rock_organ", label: "Rock Organ" },
  { value: "church_organ", label: "Church Organ" },
  { value: "reed_organ", label: "Reed Organ" },
  { value: "accordion", label: "Accordion" },
  { value: "harmonica", label: "Harmonica" },
  { value: "tango_accordion", label: "Tango Accordion" },
  { value: "acoustic_guitar_nylon", label: "Acoustic Guitar (nylon)" },
  { value: "acoustic_guitar_steel", label: "Acoustic Guitar (steel)" },
  { value: "electric_guitar_jazz", label: "Electric Guitar (jazz)" },
  { value: "electric_guitar_clean", label: "Electric Guitar (clean)" },
  { value: "electric_guitar_muted", label: "Electric Guitar (muted)" },
  { value: "overdriven_guitar", label: "Overdriven Guitar" },
  { value: "distortion_guitar", label: "Distortion Guitar" },
  { value: "guitar_harmonics", label: "Guitar Harmonics" },
  { value: "acoustic_bass", label: "Acoustic Bass" },
  { value: "electric_bass_finger", label: "Electric Bass (finger)" },
  { value: "electric_bass_pick", label: "Electric Bass (pick)" },
  { value: "fretless_bass", label: "Fretless Bass" },
  { value: "slap_bass_1", label: "Slap Bass 1" },
  { value: "slap_bass_2", label: "Slap Bass 2" },
  { value: "synth_bass_1", label: "Synth Bass 1" },
  { value: "synth_bass_2", label: "Synth Bass 2" },
  { value: "violin", label: "Violin" },
  { value: "viola", label: "Viola" },
  { value: "cello", label: "Cello" },
  { value: "contrabass", label: "Contrabass" },
  { value: "tremolo_strings", label: "Tremolo Strings" },
  { value: "pizzicato_strings", label: "Pizzicato Strings" },
  { value: "orchestral_harp", label: "Orchestral Harp" },
  { value: "timpani", label: "Timpani" },
  { value: "string_ensemble_1", label: "String Ensemble 1" },
  { value: "string_ensemble_2", label: "String Ensemble 2" },
  { value: "synthstrings_1", label: "SynthStrings 1" },
  { value: "synthstrings_2", label: "SynthStrings 2" },
  { value: "choir_aahs", label: "Choir Aahs" },
  { value: "voice_oohs", label: "Voice Oohs" },
  { value: "synth_voice", label: "Synth Voice" },
  { value: "orchestra_hit", label: "Orchestra Hit" },
  { value: "trumpet", label: "Trumpet" },
  { value: "trombone", label: "Trombone" },
  { value: "tuba", label: "Tuba" },
  { value: "muted_trumpet", label: "Muted Trumpet" },
  { value: "french_horn", label: "French Horn" },
  { value: "brass_section", label: "Brass Section" },
  { value: "synthbrass_1", label: "SynthBrass 1" },
  { value: "synthbrass_2", label: "SynthBrass 2" },
  { value: "soprano_sax", label: "Soprano Sax" },
  { value: "alto_sax", label: "Alto Sax" },
  { value: "tenor_sax", label: "Tenor Sax" },
  { value: "baritone_sax", label: "Baritone Sax" },
  { value: "oboe", label: "Oboe" },
  { value: "english_horn", label: "English Horn" },
  { value: "bassoon", label: "Bassoon" },
  { value: "clarinet", label: "Clarinet" },
  { value: "piccolo", label: "Piccolo" },
  { value: "flute", label: "Flute" },
  { value: "recorder", label: "Recorder" },
  { value: "pan_flute", label: "Pan Flute" },
  { value: "blown_bottle", label: "Blown Bottle" },
  { value: "shakuhachi", label: "Shakuhachi" },
  { value: "whistle", label: "Whistle" },
  { value: "ocarina", label: "Ocarina" },
];
